import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign} from 'node:crypto';import {Store,newState,requestPayload} from '../core.mjs';
function setup(){let now=1000;const s=new Store(newState(),()=>{},()=>now);const keys=generateKeyPairSync('ec',{namedCurve:'prime256v1'});const p=s.createPurchase(keys.publicKey.export({format:'jwk'}));const receipt=s.simulatePayment(p.id);s.publishNotice({title:'Correction',body:'Replacement or refund available.'});const req=()=>({purchaseId:p.id,nonce:s.issueChallenge(p.id).nonce,destination:'simulation-receiving-address'});const signature=r=>sign('sha256',Buffer.from(requestPayload(r)),{key:keys.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url');return{s,p,receipt,req,signature,keys,advance:()=>now+=120001};}
test('Receipt is signed; altered amount is rejected; repeated payment is idempotent',()=>{const x=setup();assert.equal(x.s.validateReceipt(x.receipt),true);assert.equal(x.s.validateReceipt({...x.receipt,amount:'50'}),false);assert.deepEqual(x.s.simulatePayment(x.p.id),x.receipt);});
test('Destination-bound signature authorizes exactly one request and one simulated payout',()=>{const x=setup(),r=x.req();const q=x.s.requestRefund(r,x.signature(r));assert.equal(q.status,'requested');assert.throws(()=>x.s.requestRefund(r,x.signature(r)),/expired|used/);const r2=x.req();assert.throws(()=>x.s.requestRefund(r2,x.signature(r2)),/already exists/);assert.equal(x.s.simulateRefund(q.id).status,'simulated');assert.throws(()=>x.s.simulateRefund(q.id),/already/);});
test('Destination substitution and wrong key fail',()=>{const x=setup(),r=x.req(),sig=x.signature(r);assert.throws(()=>x.s.requestRefund({...r,destination:'attacker-destination'},sig),/signature/);const wrong=generateKeyPairSync('ec',{namedCurve:'prime256v1'});assert.throws(()=>x.s.requestRefund(r,sign('sha256',Buffer.from(requestPayload(r)),{key:wrong.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url')),/signature/);});
test('Expired challenges and unpaid purchases fail',()=>{const x=setup(),r=x.req();x.advance();assert.throws(()=>x.s.requestRefund(r,x.signature(r)),/expired/);const k=generateKeyPairSync('ec',{namedCurve:'prime256v1'});const p=x.s.createPurchase(k.publicKey.export({format:'jwk'}));assert.throws(()=>x.s.issueChallenge(p.id),/Confirmed/);});
test('State survives serialization and receipts retain issuer identity',()=>{const x=setup();const restored=new Store(JSON.parse(JSON.stringify(x.s.state)));assert.equal(restored.validateReceipt(x.receipt),true);assert.equal(restored.state.notices.length,1);});
test('Buyer can request without a seller notice; reason is signed and persisted',()=>{const x=setup();x.s.state.notices=[];const r={...x.req(),reason:'Product does not match the description.'};const sig=x.signature(r);assert.throws(()=>x.s.requestRefund({...r,reason:'Altered reason'},sig),/signature/);const q=x.s.requestRefund(r,sig);assert.equal(q.status,'requested');assert.equal(q.reason,r.reason);assert.equal(new Store(JSON.parse(JSON.stringify(x.s.state))).state.requests[q.id].reason,r.reason);});
test('Refund reasons cannot be blank or oversized',()=>{for(const reason of ['', 'x'.repeat(1001)]){const x=setup(),r={...x.req(),reason};assert.throws(()=>x.s.requestRefund(r,x.signature(r)),/reason/);}});
test('Private keys cannot be submitted as purchase public keys',()=>{const k=generateKeyPairSync('ec',{namedCurve:'prime256v1'});assert.throws(()=>new Store().createPurchase(k.privateKey.export({format:'jwk'})),/public/);});
test('Private status requires a purpose-specific signature; tracks seller completion',()=>{const x=setup();const r=x.req();const q=x.s.requestRefund(r,x.signature(r));const query=()=>({purchaseId:x.p.id,nonce:x.s.issueChallenge(x.p.id).nonce});const key=generateKeyPairSync('ec',{namedCurve:'prime256v1'});const bad=query();assert.throws(()=>x.s.purchaseStatus(bad,sign('sha256',Buffer.from(JSON.stringify(['veylo.status.v1',bad.purchaseId,bad.nonce])),{key:key.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url')),/Invalid/);const c=query();assert.throws(()=>x.s.purchaseStatus(c,x.signature({...c,destination:'some-destination'})),/Invalid/);x.s.simulateRefund(q.id);assert.equal(x.s.state.requests[q.id].status,'simulated');});

test('Status is authenticated, single-use, and current after refund simulation',()=>{const x=setup();function read(){const r={purchaseId:x.p.id,nonce:x.s.issueChallenge(x.p.id).nonce};const sig=sign('sha256',Buffer.from(JSON.stringify(['veylo.status.v1',r.purchaseId,r.nonce])),{key:x.keys.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url');const value=x.s.purchaseStatus(r,sig);assert.throws(()=>x.s.purchaseStatus(r,sig),/expired/);return value;}assert.equal(read().refund,null);const r=x.req(),q=x.s.requestRefund(r,x.signature(r));assert.equal(read().refund.status,'requested');x.s.simulateRefund(q.id);assert.equal(read().refund.status,'simulated');});
