export const products = [
  {
    "id": "pixelpress",
    "name": "Pixelpress",
    "category": "Software",
    "description": "Resize images and export compressed JPEGs or PNGs in your browser. Your images stay on your device.",
    "price": "0.001",
    "value": 100000,
    "tone": "blue",
    "mark": "PX",
    "kind": "Offline image utility",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "format": "ZIP download",
    "download": "/api/download"
  },
  {
    "id": "contour",
    "name": "Contour",
    "category": "Design",
    "description": "Twelve original outline SVG icons for interfaces, presentations, and personal projects.",
    "price": "0.001",
    "value": 100000,
    "tone": "purple",
    "mark": "CO",
    "kind": "SVG icon collection",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "format": "ZIP download",
    "download": "/api/download"
  },
  {
    "id": "chime",
    "name": "Chime",
    "category": "Audio",
    "description": "Four original synthesized interface sounds: success, notification, tap, and completion.",
    "price": "0.001",
    "value": 100000,
    "tone": "green",
    "mark": "CH",
    "kind": "Interface sound pack",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "format": "ZIP download",
    "download": "/api/download"
  },
  {
    "id": "fieldnotes",
    "name": "Fieldnotes",
    "category": "Journals",
    "description": "A structured journal for observations, evidence, and follow-up questions.",
    "price": "0.001",
    "value": 100000,
    "tone": "terra",
    "mark": "FN",
    "kind": "Field journal",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Field Studio",
    "download": "/replacement.txt",
    "format": "Text download"
  }
];
export const legacyProducts = [
  {
    "id": "weekform",
    "name": "Weekform",
    "category": "Planning",
    "description": "A weekly planning template with priorities, focus blocks, and a practical review.",
    "price": "0.002",
    "value": 200000,
    "tone": "blue",
    "mark": "WF",
    "kind": "Weekly planner",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "download": "/downloads/weekform.txt"
  },
  {
    "id": "scopekit",
    "name": "Scopekit",
    "category": "Business",
    "description": "A project brief template for agreeing scope, deliverables, and acceptance criteria.",
    "price": "0.003",
    "value": 300000,
    "tone": "purple",
    "mark": "SK",
    "kind": "Project brief",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "download": "/downloads/scopekit.txt"
  },
  {
    "id": "stillroom",
    "name": "Stillroom",
    "category": "Journals",
    "description": "A quiet reflection workbook for decisions, progress, and the next small step.",
    "price": "0.0015",
    "value": 150000,
    "tone": "green",
    "mark": "SR",
    "kind": "Reflection workbook",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "download": "/downloads/stillroom.txt"
  },
  {
    "id": "launchlist",
    "name": "Launchlist",
    "category": "Business",
    "description": "A launch checklist covering product readiness, support, and release-day checks.",
    "price": "0.0025",
    "value": 250000,
    "tone": "gold",
    "mark": "LL",
    "kind": "Launch checklist",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "download": "/downloads/launchlist.txt"
  },
  {
    "id": "framebook",
    "name": "Framebook",
    "category": "Design",
    "description": "A screen-planning workbook for mapping user tasks, states, and interactions.",
    "price": "0.002",
    "value": 200000,
    "tone": "rose",
    "mark": "FB",
    "kind": "Screen planner",
    "version": "1.0",
    "asset": "ZEC",
    "seller": "Veylo Studio",
    "download": "/downloads/framebook.txt"
  }
];
export function getProduct(id="fieldnotes"){const p=[...products,...legacyProducts].find(p=>p.id===id);if(!p)throw Error("Product not found.");return {...p};}
